# Generated by Django 3.2.9 on 2021-11-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20211116_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[(2, 'hard'), (0, 'easy'), (1, 'medium')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='weight',
            field=models.CharField(choices=[(1, 'major'), (2, 'critical'), (0, 'minor')], max_length=10),
        ),
    ]
