# Generated by Django 3.2.9 on 2021-11-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20211117_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.CharField(blank=True, choices=[(2, 'learning'), (1, 'pressure'), (0, 'management')], max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[(2, 'hard'), (1, 'medium'), (0, 'easy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='weight',
            field=models.CharField(choices=[(2, 'critical'), (0, 'minor'), (1, 'major')], max_length=10),
        ),
    ]
