# Generated by Django 3.2.9 on 2021-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20211117_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[(1, 'medium'), (0, 'easy'), (2, 'hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='weight',
            field=models.CharField(choices=[(2, 'critical'), (1, 'major'), (0, 'minor')], max_length=10),
        ),
    ]
