# Generated by Django 3.2.9 on 2021-11-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20211117_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='projects',
            name='project',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='projekt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task.projects'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(2, 'done'), (0, 'not started'), (1, 'in progress')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='weight',
            field=models.CharField(choices=[(1, 'major'), (2, 'critical'), (0, 'minor')], max_length=10),
        ),
    ]
