# Generated by Django 3.2.9 on 2021-11-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20211120_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='branch',
            field=models.PositiveSmallIntegerField(choices=[(0, 'todo'), (1, 'potencjalne błedy użytkownika'), (2, 'znalezione błędy')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not started'), (1, 'In progress'), (2, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='weight',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Minor'), (1, 'Major'), (2, 'Critical')], default=0),
        ),
    ]
