# Generated by Django 3.2.9 on 2021-12-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeusing',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
