# Generated by Django 3.2.9 on 2021-12-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_task_timeusing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeusing',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
