# Generated by Django 3.2.9 on 2021-12-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_timeusing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeusing',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
