# Generated by Django 3.2.9 on 2021-12-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_task_timeusing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='branch',
            field=models.PositiveSmallIntegerField(choices=[(0, 'todo'), (1, 'potencjalne błedy użytkownika'), (2, 'znalezione błędy'), (3, 'usprawnienia')], default=0),
        ),
    ]
